### ISSUE TITLE
Give PodeLoggingMethods a name and let Write-PodeLog write to them

### ISSUE THREAD

**Issue by SeriousMikeDE** [Badgerati/Pode#1010]
### Describe the Change
I use the builtin logging method "file" and would like to add my own lines to the log file.

Write-PodeLog only works for custom methods right now and requires a name for the method to write to.

I'd like to be able to use the builtin file logging but also use Write-PodeLog to add additional content to the log file.

I guess this also applies to the other builtins terminal and EventViewer.

### Related Issues (current behavior)
Write-PodeLog does nothing but writing to enabled logging method is expected.

### Additional Context
Here's an example code which currently doesn't add the additional line:

```powershell
Import-Module -Name Pode -MaximumVersion 2.99.99

Start-PodeServer {
    Add-PodeEndpoint -Address * -Port 8080 -Protocol Http
    # activate builtin file logging
    New-PodeLoggingMethod -File -Name "TestRequests" | Enable-PodeRequestLogging
    Add-PodeRoute -Method Get -Path "/test" -ScriptBlock {
        $logtxt = "this is a test log line"
        # expect $logtxt to show up in log file
        $logtxt | Write-PodeLog -Name "TestRequests"
        Write-PodeJsonResponse -Value @{ "value" = "yes" }
    }
}
```

**Comment by Badgerati** [comment]
Hi @SeriousMikeDE,

`Write-PodeLog` actually takes the name of the "logger" itself - in this case the RequestLogging rather than the FileMethod. The File method can be re-used on multiple loggers, letting you use the same file for Requests and some custom logs.

The Request logging does have an inbuilt name, but it transforms any data sent to it into the Common Log Format. Here you'll have to add a custom logger that uses the same File method, but simply returns the raw string, and then use this custom logger name on `Write-PodeLog`:

```powershell
Import-Module -Name Pode -MaximumVersion 2.99.99

Start-PodeServer {
    Add-PodeEndpoint -Address * -Port 8080 -Protocol Http

    $fileMethod = New-PodeLoggingMethod -File -Name "TestRequests"
    $fileMethod | Enable-PodeRequestLogging
    $fileMethod | Add-PodeLogger -Name 'FileLog' -ScriptBlock {
        param($item)
        return "$($item)"
    }

    Add-PodeRoute -Method Get -Path "/test" -ScriptBlock {
        $logtxt = "this is a test log line"
        $logtxt | Write-PodeLog -Name "FileLog"
        Write-PodeJsonResponse -Value @{ "value" = "yes" }
    }
}
```

Hope that helps! :)

**Comment by SeriousMikeDE** [comment]
Thanks for the reply. I'll try your solution once I'm in the office again.

**Comment by SeriousMikeDE** [comment]
Works like a charm!

Thanks for helping me out :)
