### ISSUE TITLE
Slow performance

### ISSUE THREAD

**Issue by abolinhas** [Badgerati/Pode#1031]
Hi
I'm creating an api to check if a user is member of a group.
Directly in powershell, the cmd takes only 41ms to exectue.
```
PS C:\Users\Administrator> measure-command {Get-ADGroupMember -Identity itchart -Recursive -Server stie2.articatech.local | Where-Object {$_. SamAccountName -eq "admin2"}}


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 41
Ticks             : 419454
TotalDays         : 4.85479166666667E-07
TotalHours        : 1.16515E-05
TotalMinutes      : 0.00069909
TotalSeconds      : 0.0419454
TotalMilliseconds : 41.9454
```

But over Pode the response time takes 120ms or more, this is my code
```
#Start Pode Server
Import-Module ActiveDirectory
Start-PodeServer -Threads 20 {

    #Attach port 8000 to the local machine address and use HTTP protocol
    Add-PodeEndpoint -Address 192.168.60.30 -Port 8083 -Protocol HTTP

    #Create route and return a static value
    Add-PodeRoute -Method Get -Path '/static' -ScriptBlock {
        $data = Get-ADGroupMember -Identity itchart -Recursive -Server stie2.articatech.local | Where-Object {$_. SamAccountName -eq "admin2"}
        if($data.Count -eq 0) {
            Write-PodeTextResponse -Value 'false'  #-Cache -MaxAge 1800
        }
        else {
            Write-PodeTextResponse -Value 'true' #-Cache -MaxAge 1800
        }  
       
    }
}
```
![Screenshot_63](https://user-images.githubusercontent.com/3245485/202830935-40c69385-8c43-4760-a40e-88b888a86f35.png)

I'am doing something wrong?
Best Regards

**Comment by Badgerati** [comment]
Hi @abolinhas,

I would say this is expected. The overhead added from Pode will be on average an additional 40-80ms on top of the command being run in isolation. Pode needs to run a lot more logic for additional request parsing and response building, which adds extra time.

For example, this command takes 2-5ms for me in isolation:
```powershell
Get-ChildItem c:\ | Select-Object Name
```

but once being run via Pode the request>response takes 40-70ms. And via a browser it'll add a few more milliseconds for rendering the DOM.

You could speed up the command you're running by removing the `|` and splitting it out into separate calls, and using `foreach`  over `Where-Object`:
```powershell
$members = Get-ADGroupMember -Identity itchart -Recursive -Server stie2.articatech.local
$members = @(foreach ($mem in $members) {
    if ($mem.samAccountName -eq 'admin2') {
        $mem
    }
})
```

**Comment by abolinhas** [comment]
Hi
Thanks i will try it
This service need to support around 4k clients doing an avarange of 10rps each client.
Pode can handle such number of clients/request? 
Do you recomend use Kestrel instead?
Best regards

**Comment by Badgerati** [comment]
H @abolinhas,

If you're looking for something that could handle a potential 40,000rps you would be far better off with pure ASP.NET and Kestrel (that, or Go/Rust). However, even there, like with Pode, you're going to very more than likely need horizontal scaling configured to handle the load.

I ran a quick performance test with a setup similar to yours (~120ms req duration and 20 threads), and I can get up to ~170rps with a single instance of Pode. (running on a Windows 10 laptop, 16GB RAM, 4 cores).

It also depends on the type of requests you're expecting. If they'll all for the AD example above, then yes, use something else. But if only a handful will be this, and the rest much simpler requests, I have had Pode doing ~300rps before. You could also implement caching as well - such as not running the same `Get-ADGroupMemeber` query every time, but only every now and then.

**Comment by abolinhas** [comment]
Thanks for the help.
I will close it.

**Comment by idanmashaal** [comment]
Hi, @Badgerati 
Apologies for re-opening this question, but I'm experiencing something similar.
I have a module that I'm using inside of Pode. Normal run of this module via CLI takes ~1500ms.
Module returns string output, I wrap that with <pre> inside Pode and timing is the same.
If I run this inside Pode with 1 thread, I get the same time, which is around ~1600ms.
If I use Pode with 2 threads, something interesting happens:
First request will take ~1600ms
Second request will take ~9000ms
Third request will take ~1600ms
Fourth request will take ~900ms
and so forth....

If I add more than 2 threads, the first request will be fast, then all other requests will be slow until served from the first thread.
I added timing inside my external module and can verify that the slowness comes from the reason Pode is calling the module. 
Is there something that can be done to optimize this, other than running multiple instances of Pode with 1 thread on a given machine with a load-balancer?

Thanks,
Idan.

**Comment by Badgerati** [comment]
Hey @fatherofinvention,

A lot of this is going to be based on the spec of the hardware, the number of threads/runspaces enabled within Pode, and the request duration. For example, I've clocked Pode at ~300 rps myself, but this was on very simple and fast API calls - in which case to support 40,000 rps would be 133 instances of Pode.

One thing I should highlight is that I've never properly load or stress tested Pode, the only "performance" testing I've ever done is running a Pode server locally whilst running k6 scripts against it locally - all on the same machine, and k6 uses a lot of CPU when running. I've thought about trying to set up something to do it properly, but I just don't have the resources to do it.

I know there are people on Discord who have a Pode server running, and have 4k machines talking back to it as well - and they've said it handles it perfectly fine! Though I'm not sure what the request throughput is that they're doing.

Kestrel I would just forget, and it's the reason I stopped supporting fully Pode.Kestrel; since all of the request processing gets queued and then handled by PowerShell, that PowerShell processing becomes *the* bottleneck. Because of that bottleneck, Pode's socket listener and Kestrel clocked the same speeds. In Pode v1.0 Kestrel did make a speed difference, but since v2.0 Pode has just been on-par.

In theory, if you had powerful enough machines with load balancing, scaling, caching, and other optimisations then yes: you could handle 40,000 rps, I just don't know how many instances of Pode would actually be required. And it's also still dependant on request duration as well - if one API call took 1s that would greatly affect performance.

Without proper metrics to base it on, I'd say Pode would be best for handful to hundreds of users with the right optimisations. Or hundreds to thousands of machines if they're calling fast APIs in a "call-back-home" or "health status" manner.

Do you know what sorts of calls these users are going to be making, and the durations of requests etc.? If you do use Pode for this, please let me know, because I'd be very interested to know how it's going, and to know the results of any performance testing you might conduct yourself - if we can make Pode go faster, I'm all for it!

(one way I know of how to make Pode more performant is to move everything into .NET, and make Pode a compiled/binary PowerShell module instead. Something I've entertained for v3, but obviously it's a lot of work)

I know it's not the most helpful, but I hope that helps!

**Comment by Badgerati** [comment]
Thanks @fatherofinvention, that's really useful, and some interesting numbers as well! From the tool you ran, you didn't happen to get the RPS/RPM at all? I'll keep an eye here, as I'd be very interested to learn what you find as well 😄 

The compiled module idea is a complicated one, as to do it would mean converting all of Pode over to C#. That would definitely restrict contributions and is why I've been very hesitant to do it, so any performance gains we can get in Pode current setup would be the most ideal.
