### ISSUE TITLE
Mixing Pode.Web in Pode Views

### ISSUE THREAD

**Issue by fatherofinvention** [Badgerati/Pode#1075]
### Question
I am playing around with custom HTML in Pode views and thought it would be cool to also be able to leverage Pode.Web when needed but cannot get them to render. Is this possible? Here is a basic example:

```pode
<!DOCTYPE html>
<html lang="en">
  <title>Mixing Pode.Web With Pode Views</title>
  <body>
<div class="container">
  <div class="columns">
    <div class="column col-12">
    $(New-PodeWebCard -Name 'Test' -Content @(
        New-PodeWebForm -Name 'TestingIt091827' -ScriptBlock {
			#noop
        } -Content @(
            New-PodeWebTextbox -Name 'TestName' -DisplayName 'Name'
            New-PodeWebRadio -Name 'TestScope' -DisplayName 'Scope' -Options @('AllUsers', 'CurrentUser')
        ) 
    ))
    </div>
  </div>
</div>
  </body>
</html>
```

**Comment by Badgerati** [comment]
Hi @fatherofinvention,

It's an interesting idea, though with how Pode.Web works at the moment it's not currently possible. Calling `New-PodeWebCard`, etc., will each return a hashtable defining the element which is then used in Pode.Web to dynamically build a lot of Pode Views.

Calling them in isolation, within custom Pode Views, they will simply return bare hashtables 😛 

It is teeechnically possible, but would require a change in Pode.Web to render the required HTML, something like this possibly:
```powershell
<!DOCTYPE html>
<html lang="en">
  <title>Mixing Pode.Web With Pode Views</title>
  <body>
<div class="container">
  <div class="columns">
    <div class="column col-12">
    $(ConvertTo-PodeWebHtml (New-PodeWebCard -Name 'Test' -Content @(
        New-PodeWebForm -Name 'TestingIt091827' -ScriptBlock {
			#noop
        } -Content @(
            New-PodeWebTextbox -Name 'TestName' -DisplayName 'Name'
            New-PodeWebRadio -Name 'TestScope' -DisplayName 'Scope' -Options @('AllUsers', 'CurrentUser')
        ) 
    )))
    </div>
  </div>
</div>
  </body>
</html>
```

It'll also need helper functions to load the CSS (this could be optional), and also the required JavaScript (definitely mandatory, otherwise controls wouldn't work).

Might be a good one to raise over on Pode.Web 😄

**Comment by fatherofinvention** [comment]
Thanks @Badgerati! II'll close this and open a new issue in the Pode.Web repo as suggested. Just to give you a little more context, I love how easy it is to build with Pode and Pode.Web, but I'm not a fan of the default Bootstrap styling. When I learned about views, I got really excited because it makes it super simple to write my own HTML and style it however I like, plus add PowerShell logic. However, there are a few things I'd love to use from Pode.Web (like file upload), so it would be great if I could pick and choose what I need from Pode.Web and use custom markup, styles, etc. the rest of the time.
