### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by LLIT** [Badgerati/Pode#22]
Hi Matthew,

When running Pode i have noticed the CPU usage in idle is arround 40% in my test environments.
Do you know if it is a .Net "feature" on Windows? (Both 2012 R2)

**Comment by Badgerati** [comment]
Annoyingly it's a .NET HttpListener thing; when the CPU spikes it's sat on `$listener.GetContextAsync()`. I replaced that whole while loop with just `Start-Sleep -Seconds 1` and the CPU sat at a comfortable 1-2%.

I'll do some digging, see if there's a way to reduce it.

**Comment by larssb** [comment]
I concur to this. I also see it on MacOS. I could look into if it also happens on RancherOS I happen to be using at work. However, I think it does.

@Badgerati please see the below finding:

I did a debugging session in VS Code and identified the following code to be the culprit > [High CPU culprit](https://github.com/Badgerati/Pode/blob/ad6dddaa48b6c63c4441ba5968bd20697883f05e/src/Tools/WebServer.ps1#L49) ...
As soon as I out-commented that `while (!$task.IsCompleted)...` loop the CPU usage fell to 2-5%. What are we loosing then. Clearly the option to be able to press `Ctrl-C` in order to terminate the server process. I therefore tried to find a way to still have this functionality. However, during the hour I used on it I was not able to.

Could you please have a look.

Thank you very much.

**Comment by Badgerati** [comment]
Good ol' while loops; just looking for a way to wait for an incoming request without hammering the CPU (and without using a sleep!)

Thanks for running the debug! 😄

**Comment by Badgerati** [comment]
So I've been taking a look into it, and I can't seem to find a good solution of both dropping the CPU and keeping the Ctrl+C without a sleep of some kind (though I'm open to suggestions!)

What I've got so far is the following:

1. First idea is quick, simple, and a little dirty. Adding `Start-Sleep -Milliseconds 1` to the while-loop plummets the CPU usage to a normal <2%, and means we can keep the Ctrl+C for every environment while not affecting HTTP response performance drastically.

2. Second idea utilises the first idea, but has two defined code path; we could have a `-Dev` switch on the `Server` logic, and when supplied will enable Ctrl+C and use the while-loop with a 1ms sleep. When it's not supplied however, it disables the Ctrl+C and uses `$task.Wait()` instead. This way in non-dev/qa/reg environments (and containers especially) you don't really need the Ctrl+C.

For the second idea, you could set a `env:PODE_ENV` and in your code if it's `developer` then supply `-Dev:$true` otherwise `-Dev:$false`

**Comment by Badgerati** [comment]
Did some quick load testing using the simple `Start-Sleep -Milliseconds 1` in the while-loop; and performance isn't impacted at all. CPU is also normal, Ctrl+C still available.

Unless you guys want the `-Dev` feature, I can quickly push out the above as a hot-fix

**Comment by Badgerati** [comment]
I've searched the internets high and low, and there doesn't seem to be a way in powershell to listen to keyboard events - unless you start pulling in user/kernel DLLs.

Also thought about trying to use Runspaces and Timers, but both also fell short.

I'm really surprised there's no `KeyPress` event in `PowerShell.Engine`, or the fact that `[Console]::CancelKeyPress` is there but it can't be used it annoying as well.

It's late here now, so I'll throw in the quick fix tomorrow while we continue the hunt for a better way.

**Comment by Badgerati** [comment]
It'll be due to CPU cycles. ie, a quick counter and a while loop with no sleep running for 1 second counts up to 811650; but the moment the 1ms sleep comes in the same counter only get up to 64 😄 

crazy right, haha

**Comment by Badgerati** [comment]
Patch pushed out in v0.11.2

**Comment by Badgerati** [comment]
Some good news; I managed to work out how to monitor for key presses asynchronously, and how to still cleanly close Pode while keeping CPU low and allowing Ctrl+C!

The code is in the commit above ^ [422f0ed](https://github.com/Badgerati/Pode/commit/422f0edb5e6e7789ea1ff30d17cf0ab3fada5345).

The idea is to use a separate Runspace that has the current $Host and a CancellationToken supplied via the Runspace Session State. The Runspace monitors for key presses and the Ctrl-C combo, if triggered then it will call `Cancel()` on the token.

The CancellationToken is passed to the `Task.Wait` calls, so that when it's cancelled we can exit out of the server and clear up the session.

Furthermore, the separate key press listening Runspace is only created when the input isn't being redirected - so Pode running in Docker will not have this Runspace setup (unless you run the container with `-t`).

Since it can now be more easily set as optional, I could throw in the `-Dev` flag on the `Server` so the listener is only enabled when that flag is supplied? 

### Links
* https://msdn.microsoft.com/en-us/library/system.threading.cancellationtokensource(v=vs.110).aspx
* https://msdn.microsoft.com/en-us/library/dd321315(v=vs.110).aspx
* https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.host.pshostrawuserinterface.readkey?view=powershellsdk-1.1.0

**Comment by Badgerati** [comment]
or, if we do go for a flag option; maybe have a`-DisableCtrlC` instead - so other people using Pode don't sudden start having Ctrl-C being disabled! 😂

**Comment by ssugar** [comment]
I tested the 0.11.2 release on my Mac, and it was still resulting in high CPU usage (~30% - despite the sleep 1ms fix), although Ctrl-C still did work to exit.  

This new fix has resolved the high CPU issue (CPU usage is much lower - only ~4 or 5%), but now on my Mac Ctrl-C doesn't seem to exit anymore.

**Comment by Badgerati** [comment]
@ssugar Just pushed something that should hopefully fix it; the same issue occurred on Linux, so should now work on Mac as well - thinking it could just be a ps-core issue.

(Afraid a Mac is the only thing I've no access too)

**Comment by ssugar** [comment]
@Badgerati - That fixed it for me on Mac - Ctrl-C works again.  And CPU usage is much lower now.  Thanks!

**Comment by Badgerati** [comment]
Awesome; I've just added in a `-DisableCtrlC` flag for the `Server`, to disable exiting in certain environments.

**Comment by larssb** [comment]
This is great great work @Badgerati ... I like it. A name change suggestion for the -DisableCtrlC parameter. Maybe -DisableTermination or the like. Just so that we don't bind to a specific key combination.

**Comment by Badgerati** [comment]
Yes, agreed; in case we ever want to have `Esc` exit as well
