### ISSUE TITLE
Minor fix: FunctionsToExport

### ISSUE THREAD

**Issue by LLIT** [Badgerati/Pode#226]
You are missing a few Functions in your Export.

I have found these missing:
GUI
Write-PodeValueToResponse
Write-PodeValueToResponseFromFile

**Comment by Badgerati** [comment]
Hey @LLIT 

The `GUI` function is a bug, it should be there and is missing.

As for the other two (`Write-PodeValueToResponse` and `Write-PodeValueToResponseFromFile`), I removed them in #209, as they were grouped with functions that aren't documented, and not needed to be exported as they were internal - which is why they also got renamed.

Is there a flow you're using where this throws errors if they're not exported; or are you using the functions directly?

I can add them back in, just curious if there's cause to give the functions an alias/rename - like `route` or `listen` 🤔

**Comment by LLIT** [comment]
The functions Write-PodeValue.... was just discoverd by reading the code, and detecting they were missing.

It was the Gui function i was after :-)

**Comment by Badgerati** [comment]
Awesome, I'll get that added for you! :)

**Comment by Badgerati** [comment]
Gui exported in v0.28.1
