### ISSUE TITLE
Import functions from a folder into a Runspace

### ISSUE THREAD

**Issue by jeremymcgee73** [Badgerati/Pode#250]
It would be nice to add a parameter to the `import` function that will load all functions in a folder. This is nice if you are creating another module to be able to import utility functions from the module. Currently, I am loading functions individually. I have an example below:

    route get '/' (auth check login -o @{ 'failureUrl' = '/login' }) {
        param($s)

        . $(Join-Path -Path $PSScriptRoot -ChildPath '../Private/Get-ScriptMeta.ps1')
        
        Get-ScriptMeta $Path
    }

**Comment by Badgerati** [comment]
Since you're dot-sourcing, you can use the [`load`](https://badgerati.github.io/Pode/Functions/Core/Load/) function to simplify it a little bit:

```powershell
load '../Private/Get-ScriptMeta.ps1'
```

That being said, adding support to `import` and `load` to automatically load all modules/scripts within a directory would be useful!

Oh also, using `import '../Private/Get-ScriptMeta.ps1'` actually works and imports the script into the runspaces 😃

**Comment by jeremymcgee73** [comment]
Awesome! Thank you! I switched to using `load` like this.

```
Server {
    Get-ChildItem "$PSScriptRoot/../Private/*.ps1" | ForEach-Object{
        import $_.FullName
    }
}
```
`

**Comment by Badgerati** [comment]
I've made it now so that `import` and `load` can have wildcard paths. Or just a directory path; in which case `import` will look for `*.ps*1` files, and `load` will look for `*.ps1` files.

Means you can now do:

```powershell
server {
    import '$PSScriptRoot/../Private/*.ps1'
}
```

😄
