### ISSUE TITLE
Feature: SignalR on Pode

### ISSUE THREAD

**Issue by LLIT** [Badgerati/Pode#259]
In one of my many projects using Pode, it would be a fantastic feature to use SignalR to talk back to a web client.
I think it will require Pode to work as a "Hub" to direct traffic to a specific url.

I know it is possible to do a  simple JavaScript loop to request the API, but it will result in a noisy client.

**Comment by Badgerati** [comment]
This is an interesting idea, I had to look into SignalR as well! 😂 

From what I can gather, you'd have to run a SignalR hub, rather than a Pode one. Then your client/website connects to that using some JS library.

For your Pode server though, I'm guessing this is where we'd need to write the logic in so that your Pode server can connect to your SignalR hub? Allowing you to send messages for broadcasting to clients.

Is this roughly what you're thinking, @LLIT ?

**Comment by LLIT** [comment]
For now I will just fix it with local Javascript...

**Comment by Badgerati** [comment]
It's no SignalR, but I've started implementing WebSocket support in #395

**Comment by Badgerati** [comment]
With Pode's WebSocket support, I'm closing this. If there's ever a need for SignalR, then it could be done as a `Pode.SignalR` extension module.
