### ISSUE TITLE
Question: Auth for rest api

### ISSUE THREAD

**Issue by LxLeChat** [Badgerati/Pode#274]
Hi :) Amazing work!!!!
Quick question, do you have an authentification example for a full rest server ?

I want to implement some kind of auth for a small server i created. I can already limit the access to only one ip (a web server), and use ssl but i want to implement some kind of auth mechanism wich does not involve forms.

in your doc, auth mechanism only use  forms. Is there another way ? 

Any idea ? maybe implementing a middleware, with some db behind holding secrets ?

Thanks again for you work ! (and sorry for my english ... )

**Comment by LxLeChat** [comment]
ah maybe it is csrf ... sorry :)

**Comment by Badgerati** [comment]
Hey @LxLeChat , and thanks!

You can find an example in the docs which uses Basic authorization: https://badgerati.github.io/Pode/Tutorials/Authentication/Basic/. This will let you pass usernames/passwords in a requests header without the need for forms.

For CSRF, that's more to help prevent cross-site request forgery attacks, rather than authentication - if you're writing a REST API with no frontend, it's likely you might not need this.

Hope that helps! 😄

**Comment by LxLeChat** [comment]
alright ! pretty obvious :) thanks !
