### ISSUE TITLE
how to use the CSRF Tokens

### ISSUE THREAD

**Issue by jhainau** [Badgerati/Pode#445]
### Question
Using your example, I was able to create a CSRF token, then use it in your example POST request, and was able to retrieve results, but I don't know how to use the token with Get requests (or other requests where a body is not supplied). 

I then tried to use the same token during the same session for another request, but got 403 - Invalid CSRF Token.  
#### Goal:
I was hoping to do something like the following:
  get /login : receive login form
  post /login : submit form with username and login - convert username/password to PSCredential and Validate against AD - receive token

#### All subsequent requests while token has not expired:
invoke-restmethod -mehtod get/post/put/etc -header @{'authorization' = "CSRF [Token]"} -url ...
I was thinking similar to a bearer token... 
I realize this is not how the CSRF token works, but I was hoping there was something similar available, or some other way to accomplish what I need

When finished and don't want to have an unexpired token languishing:
invoke-restmethod -method Delete /logout -headers @{"Authorization" = "CSRF [Token]"}

I need to be able to keep the authorization in either the header or body (and just never use get except to get the initial token) because the software tool I am using is not capable of maintaining session cookies. It has built-in support for basic auth, but my organization will not allow me to use Basic Auth.

Please forgive my ignorance

**Comment by Badgerati** [comment]
Hey @jhainau,

Yeah, you're right, that's definitely not how CSRF works! 😂 I went over the docs for your initial questions, and the CSRF ones could probably do with a little bit of a rewrite! But, for you first question:

> Do I need to generate a new token for every request?

Yes, CSRF tokens are always one-time only. A new token will be generated for each request - so everytime you reload a login page, for example, a new token is generated. They aren't cached, or kept any longer than they need to be.

> how to use the token with Get requests (or other requests where a body is not supplied)?

On GET requests, CSRF by default isn't typically used on them, but you can tell it too. [here](https://badgerati.github.io/Pode/Tutorials/Middleware/Types/CSRF/#get-podecsrfmiddleware) you'll see that GET routes are ignored by default, and you can set `-IgnoreMethods @()` on `Initialize-PodeCsrf` and `Enable-PodeCsrfMiddleware` and force CSRF to work on all methods.

To supply the CSRF token to routes that don't use a payload, it's briefly mentioned [here](https://badgerati.github.io/Pode/Tutorials/Middleware/Types/CSRF/#new-podecsrftoken). You can also supply the `pode.csrf` value in the querystring or as a header, such as:

* `http://localhost:8080/page?pode.csrf=<token>`, or
* `-Header @{ 'pode.csrf' = '<token>' }`

Because of the way CSRF tokens work, I'm afraid you won't be able to use them as an authorization method 😞 

Currently in Pode using sessions directly via a REST API isn't supported - because of the fact they store the session in cookies, BUT! I have thought about extending sessions to work with headers, so the session comes back in some `X-Pode-SessionId` header on the response. This header can then be used in subsequent REST API requests, and destroyed via one as well.

I'll look at writing up that last part soon, but I hope this helps! (I'll also add the docs label to this, to rewrite the CSRF docs).

**Comment by jhainau** [comment]
I look forward to testing this out when it's ready. It sounds very promising

**Comment by Badgerati** [comment]
The new session management with headers can be [found here](https://badgerati.github.io/Pode/Tutorials/Routes/Examples/RestApiSessions/). This should replace what you were originally attempting to do with CSRF tokens.

If you need to have the initial webpage for logging in, you can now get the auth'd SessionId from within Pode by using [`Get-PodeSessionId`](https://badgerati.github.io/Pode/Functions/Middleware/Get-PodeSessionId/) in the POST login route.

I'm gonna close this issue, but if you need any help feel free to raise another or come chat in [gitter](https://gitter.im/Badgerati/Pode?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge) 😄
