### ISSUE TITLE
Limiting requests per Endpoint/Route natively

### ISSUE THREAD

**Issue by ArieHein** [Badgerati/Pode#524]
Note: this could be a limitation of current documentation.

Today using Add-PodeLimitRule, allows you to limit requests on IP or basically per host.
Since its basically a built-in middleware you can extend/override it in your own custom middleware but it is still per host.
You can at this point add some logic to test the endpoint and route and make the logic of limiting change based on them.
But that's too much of a hassle... :)

It would be nice to have something like this:

Currently:
`Add-PodeLimitRule -Type IP -Values 127.0.0.1 -Limit 5 -Seconds 1`

Suggested:
`Add-PodeLimitRule -Type Endpoint -Name 'myEndPoint' -Limit 5 -Seconds 1`

Alternatively
`Add-PodeEndPointLimitRule -Name 'myEndPoint' -Limit 5 -Seconds 1`

Suggested:
`Add-PodeLimitRule -Type Route -Name 'myRoute' -Limit 5 -Seconds 1`

Alternatively:
`Add-PodeRouteLimitRule -Name 'myRoute' -Limit 5 -Seconds 1`

**Comment by Badgerati** [comment]
With the current format, the initial suggested idea would fit better:

```powershell
Add-PodeLimitRule -Type Route -Values '/path' -Limit 5 -Seconds 1
Add-PodeLimitRule -Type Endpoint -Values 'Name' -Limit 5 -Seconds 1
```

If a v1.9.0 happens, I may look at adding this there, otherwise it'll be in v2.0.0.

(and depending on what happens with the Auth functions in v2.0.0, the format could switch to something like `Add-PodeLimitRouteRule -Path -Etc` - so the alternative suggestion)
