### ISSUE TITLE
OpenAPI in route requests Title parameter

### ISSUE THREAD

**Issue by jackvaughanjr** [Badgerati/Pode#654]
### Describe the Bug
When sending a call to a route configured as in the example provided [here](https://badgerati.github.io/Pode/Tutorials/OpenAPI/#get-definition), the pode console asks for a Title parameter.

### Steps To Reproduce
Add the following route:
```powershell
Add-PodeRoute -Method Get -Path '/' -ScriptBlock {
    if ($WebEvent.Query.openapi -eq 1) {
        Get-PodeOpenApiDefinition | Write-PodeJsonResponse
    }
}
```
Navigate to the route in Chrome or make an API call in Postman.
The following is presented in the PowerShell window:
```powershell
cmdlet Get-PodeOpenApiDefinition at command pipeline position 1
Supply values for the following parameters:
Title:
```
(If I enter a title, the call fails. If I use the -Title parameter, the call fails.)
In the error log, I see the following:
```powershell
Category: MetadataError: (:) [Get-PodeOpenApiDefinition], ValidationMetadataException
Message: The variable cannot be validated because the value  is not a valid value for the Version variable.
StackTrace: at Get-PodeOpenApiDefinition, C:\Program Files\WindowsPowerShell\Modules\pode\2.0.3\Public\OpenApi.ps1: line 157
```
It looks like the parameters on `Get-PodeOpenApiDefinition` are mandatory when they shouldn't be?

**Comment by Badgerati** [comment]
Hey @jackvaughanjr,

Yep, you're right! `Title` and `Version` were set as mandatory by mistake. I've removed the mandatory setting on them, so if not supplied they default to the values from `Enable-PodeOpenApi`. If, after that, they still empty, an error is thrown - which shouldn't happen, as they are mandatory on `Enable-PodeOpenApi`.

This should now be fixed in the above commit, thanks! 😃
