### ISSUE TITLE
Get-PodeConsoleKey triggering debug mode running under IIS

### ISSUE THREAD

**Issue by flatyak** [Badgerati/Pode#741]
### Describe the Bug
Pode application running under IIS intermittently crashes, logging the following message:

```
Entering debug mode. Use h or ? for help.

At C:\Program Files\PowerShell\Modules\Pode\2.0.3\Public\Core.ps1:176 char:13
+ $key = Get-PodeConsoleKey
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
[DBG]: PS D:\wwwroot\sitename>> 
```

### Steps To Reproduce
This happens when the application is idle (no requests for ten minutes or more)

### Expected Behavior
Application stays running and does not log errors

### Platform
 - OS: [e.g. iOS, Windows] Windows Server 2019
 - Browser: [e.g. Chrome, Safari] n/a
 - Versions:
   - Pode: [e.g. Pode v1.7.3] Tested with 2.0.3 and 2.2.3
   - PowerShell: [e.g. PS6.2.1] 7.0.4

### Additional Context
The line mentioned in the error looks like it should not be executed when running under IIS (see comment on line 155) but there is nothing actually checking this and preventing it

**Comment by RobinBeismann** [comment]
This sounds like IIS is recycling the App Pool, can you check if there is time based recycling enabled?

**Comment by flatyak** [comment]
I don't think so - I have set the app pool to recycle only at a scheduled time (middle of the night) but it is also set for on-demand, configuration changes, unhealthy ISAPI
I can see what I think is the recycle request arriving shortly after the debug message so it might be something is triggering it (not sure how soon after the debug as there is no timestamp on that line)
```
127.0.0.1 - - [18/May/2021:16:28:51 +01:00] "POST /iisintegration HTTP/1.1" 404 1120 "-" "-"
```

Of course, it's perfectly possible I have set up something incorrectly in IIS

**Comment by Badgerati** [comment]
Hey,

I have this to, it's a debug line from PowerShell when IIS interrupts Pode waiting for a key press, and I've only currently seen it appear when you do either:

* `iisreset`
* Manually restart the site, or recycle the app pool
* The site goes idle, hits the app pools "idle timeout" and shuts down

and then it'll either appear immediately, or when you next try to call the site.

It's probably worth checking the app pool idle timeout value, usually the default is 20 - if it is, set it to 0 to never go to sleep.

**Comment by flatyak** [comment]
Ah, that might well be it.  Does seem to happen 20 minutes after being idle.

I've changed the app pool idle timeout to 0 (this is under Advanced Settings for anyone else having this problem) and after some brief testing it appears to be staying up.

Is this a bug?  Should Pode be listening for keypresses when running under IIS or is this just a side effect of the app pool recycling so maybe just noting the idle timeout setting in the IIS hosting doc?

Thanks for your help - Pode is amazingly good!

**Comment by MohnJcAfee** [comment]
Currently facing the same Issue (Pode 2.2.3 ,latest PS7, WinServer 2016 and IIS with all patches) although I'm not sure if setting the app pool timeout has the desired effect. It breaks into debug pretty much exactly after each hour passed not affected by actual usage of the API setup by Pode. Until now I only tried setting the timeout to way higher values than 20 minutes but currently testing a 0 timeout.

**Comment by Badgerati** [comment]
So while Pode is running it enters a loop, to prevent it from exiting immediately. Within that loop, `Get-PodeConsoleKey` just does a quick check to see if any keys were pressed, if it detects Ctrl+R or B, then it restarts Pode or opens the browser (Ctrl+C is disabled when behind IIS) - both of which won't happen anyway since it's running behind IIS.

(Worth noting that restarting Pode won't affect the app-pool, Pode does a quick refresh of its own state)

To absolutely make sure checking for a key doesn't cause issues, I commented it out completely, and the debug line just moved to the next line. (This displayed like clockwork, using an idle timeout of 5mins)

Looking at the docs for IIS/Out-of-Process: it seems that when the IIS site/app-pool restart/recycle, IIS enters a temporary debug state to kill the PowerShell runspaces - which is why the debug line appears in the logs. It's quite ugly, and unfortunately there doesn't seem to be too much I can do about it 😕 

Setting the Idle Timeout to 0 is one way to stop it, but also there's the Recycling Interval (set to 0) and Recycling Specific Times (remove all) - these can also be found under the app pool's advanced settings. In the IIS docs, it also seems doing this isn't 100% bullet proof, and because it's out-of-process IIS will just recycle itself at times. There's also the option for IIS to start your site after a recycle: [can be found here](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/advanced?view=aspnetcore-5.0#application-initialization-module-and-idle-timeout)

It's also worth checking there's definitely nothing on the server that is forcing app-pool recycles. I remember one time at my work where we thought we were going crazy, and turns out there was a sneaky scheduled task running iisreset every 6hrs!! 🙈 

If you think it might be crashing, Pode should throw an error which will be visible in the log file. You can enable any errors to be written by adding the following in your `Start-PodeServer` scriptblock:
```powershell
New-PodeLoggingMethod -Terminal | Enable-PodeErrorLogging
```
> though if it is a full on exception that causes the server to crash, you shouldn't need that line at all

You can also see if any of the app-pools on the server have recently recycled by running the following:
```powershell
Get-CimInstance -classname win32_process -filter "Name like '%w3wp%'" | Select-Object name, Processid, commandline, creationdate
```

(all of this I will add into the Pode IIS docs)

Hope all of this helps!

**Comment by flatyak** [comment]
Great answer.

I can confirm that setting the app pool idle-timeout to zero has resolved the issue for me.  Checking back through the logs it was happening after being idle for exactly 20 minutes which ties in with the default for this

Thanks for your help - I've left the issue open as MohnJcAfee seems to still be having problems

**Comment by RobinBeismann** [comment]
Ah yeah, I just realized that I never stumbled into this as all our Pode instances sit behind a load balancer that probes it all 5 seconds and therefor the AppPool never idles out.

**Comment by Badgerati** [comment]
I did a little more digging, and I think I might be able to make Pode terminate gracefully on app-pool recycle.

I found this issue: https://github.com/aspnet/AspNetCoreModule/issues/115 which shows that IIS actually attempts to hit `POST /iisintegration` before killing the process. In the request log, it is actually called on recycle, so I might test to see if I can gracefully terminate and stop those debug lines!

**Comment by Badgerati** [comment]
I've added to the documentation about IIS recycling, and the debug lines.

I've also added in support for the `/iisintegration` endpoint that IIS uses. This means Pode can gracefully shutdown when IIS recycles, instead of forcibly terminating and showing those debug lines in the log.

If anyone would like to test, it's in the above commit 😃 and it now also includes IIS token validation on requests, too.
