### ISSUE TITLE
Change in global variable in a module is not recognized by Pode

### ISSUE THREAD

**Issue by datenschieber** [Badgerati/Pode#755]
### Change in global variable in a module is not recognized by Pode
I want to use one of my little modules in Pode. One module initializes a global variable with a default value during import. The module also contains an advanced function that updates the value of the global variable.

When I use my module from a simple script I can use and update the variable as intended. But when I use my module in my Pode environment the changes to the variable made via the advanced function are not recognized by the Pode environment (e.g. Pode files).

Maybe it is something with runspaces (a topic which I am not familiar with)... Any idea how the problem can be solved?

### Steps To Reproduce
mymodule.psm1:
```
$Global:myVar = "Initialized"

function Update-MyVar {
  $Global:myVar = "Updated"
}
```

mypode.ps1
```
Import-Module Pode
Import-Module MyModule

Write-Host $Global:myVar  # => Initialized
Update-MyVar
Write-Host $Global:myVar  # => Updated

Start-PodeServer {
   Add-PodeEndpoint -Address localhost -Port 8080 -Protocol Http

   Add-PodeRoute -Method Get -Path '/' -ScriptBlock {
      Write-PodeJsonResponse -Value @{ myVar = $Global:myVar }  # => {"myVar":"Initialized"} !!!
      # Write-PodeJsonResponse -Value @{ myVar = $using:Global:myVar }  doesn't work
   }
}
```

### Expected Behavior
Write-PodeJsonResponse should return {"myVar":"Updated"} instead of {"myVar":"Initialized"}.

### Platform
 - Versions:
   - Pode: 2.2.3
   - PowerShell: 7.1.3 (Core)

**Comment by Badgerati** [comment]
Hey @datenschieber,

You're correct, this is definitely down to runspaces 😃 Each runspace is effectively its own PowerShell instance, so a `$global:` variable only applies to that runspace, and not the others. The reason `$global:myVar` exists in the route, is because Pode automatically loads the `MyModule` module into all other runspaces. So as far as the route is concerned, the variable has only just been initialised - unlike the variable in the main runspace, which has been initialised and updated.

You were close with `$using:global:myVar`, instead `$using:myVar` should work just the same. Just be aware, that changing the variable's value anywhere won't be reflected in other runspaces.

The only real way to get around this is to use `Set-PodeState` and `Get-PodeState` ([docs](https://badgerati.github.io/Pode/Tutorials/SharedState/)), as these will let you share a value cross-runspace and be updatable cross-runspace.

**Comment by datenschieber** [comment]
Thanks for the explanation, @Badgerati !

Set- and Get-PodeState together with Lock-PodeObject solved my problem perfectly! Thanks for your support! 👍 🤘
