### ISSUE TITLE
Missing Functions page on readthedocs.io

### ISSUE THREAD

**Issue by phatmandrake** [Badgerati/Pode#805]
`https://pode.readthedocs.io/` does not have the "Functions" page that `https://badgerati.github.io/` has. I couldn't figure out what was going on for the longest until I realized they were two different websites. They appear to be synchronized otherwise having receive the 2.41 changes.

**Comment by Badgerati** [comment]
I officially host the documentation on `https://badgerati.github.io/Pode`, and that's where everything links to, and where the README takes you to as well; including Pode.Web.

Logging into readthedocs it looks like somehow it's been doing the docs for just Pode, and I don't even remember ever setting it up! From what I can see it's just running mkdocs and that's it, and the Functions pages are generated using PlatyPS which is why they won't be there.

The official docs are here: `https://badgerati.github.io/Pode`. I would disable the readthedocs one, but I've no idea who else is using it :/

I believe mkdocs now has support for a news-ticker across the top, so I could look into adding one of those to inform people for a while and then close it down 🤔

**Comment by phatmandrake** [comment]
I think that'd be best if anyone is like me I got dissuaded from Pode initially when I couldn't find the functions page. Not entirely sure how I found the readthedocs versioon first.
