### ISSUE TITLE
Missing ntlm schema documentation

### ISSUE THREAD

**Issue by atriumcarceri** [Badgerati/Pode#807]
### Describe the Change
Hi, badgerati.
First at all, great thanks for that beautiful framework.

In docs i not found describes about transparent auth for windows users. In http net listener class, auth schema "Negotiate" gives needed result:
Try ntlm by current logged user, if no - try basic.
But after reading some issues i understood that in pode implemented custom class.

So how is possible, to make this?

This variant give only basic

```
New-PodeAuthScheme -Basic  | Add-PodeAuthWindowsAd -Name 'Login' -Fqdn 'domain.local' -Domain 'DOMAIN'

Add-PodeRoute -Method Get -Path '/' -Authentication 'Login' -ScriptBlock {
    Write-PodeViewResponse -Path 'index'
}
```

### Additional Context
Add any other context or screenshots about the enhancement request here.

**Comment by RobinBeismann** [comment]
For seamless Windows authentication you'll need to run Pode as IIS Application and you should make sure that IIS only accepts Kerberos and not NTLMv2 as NTLM is deprecated since a long time, unsecure and being disabled in more and more environments due to the recent PetitPotan Vulnerability for a good reason.

The docs describe the IIS configuration and Windows Authentication.

**Comment by Badgerati** [comment]
Hi @atriumcarceri,

Out-of-the-box Pode doesn't support this however, as @RobinBeismann states, this can be achieved when [hosting Pode with IIS](https://badgerati.github.io/Pode/Hosting/IIS/), and letting IIS deal with Windows Authenticaion instead of Pode :)

**Comment by atriumcarceri** [comment]
Okay, many thanks for feedback. 
So i made it with oauth with keycloak. Thats work perfectly.

**Comment by RobinBeismann** [comment]
@atriumcarceri OAuth2 is probably the better choice anyway as it is more modern.
