### ISSUE TITLE
How to run a separate PS script inside a route? 

### ISSUE THREAD

**Issue by robinmalik** [Badgerati/Pode#890]
Hi,

I couldn't find this documented anywhere, but I'd like to run a separate PowerShell script inside a route, asynchronously. 

I thought perhaps `Add-PodeSchedule` could give me a way to do it, but I only need to run this once and immediately and it doesn't appear to offer that.

I also noticed the -FilePath parameter for `Add-PodeRoute` and `Add-PodeSignalRoute` - something I missed before - but this seems to spawn a PS window that immediately disappears and doesn't do anything. The separate script is not specifically Pode code, but _does stuff_ and then uses `Invoke-RestMethod` to send JSON to route defined within Pode.

Is it possible at all?

Thanks,

Robin

**Comment by Badgerati** [comment]
Hey @robinmalik,

The `-FilePath` spawning a new process is a bit strange 🤔 all it does it load the content of a file, convert it to a scriptblock, and use that for the route's logic. I'll have to look into that one.

For the script, you can actually use `Add-PodeSchedule`, but you basically have to "trick" it to never run, and then use `Invoke-PodeSchedule` to trigger it's logic async from routes:

```powershell
# this tricks a schedule to never run until the year 9999
Add-PodeSchedule -Name 'Example' -Cron '@annually' -StartTime ([datetime]::MaxValue)

# and then in a route, you can invoke the schedule:
Add-PodeRoute -Method Get -Path '/example' -ScriptBlock {
    # triggers the schedule to run, async
    Invoke-PodeSchedule -Name 'Example'
}
```

It's a bit dirty, but does the trick.

I'm thinking about adding in a "Routine" style system that I put into Pode.Game, but into Pode. Where you can setup scripts, like the schedule above, but they only run when manually invoked - possibly async by default with an optional `-Wait` switch 🤔 That way you don't have to worry about what happens if we get to the year 9999! 😂

**Comment by robinmalik** [comment]
Hey. Thanks for the quick reply. I've had a go at implementing this but to no avail currently. The route triggers, but I get an error generated: 

```
Category: OperationStopped: (Schedule 'Example' does not exist:String) [], RuntimeException
Message: Schedule 'Example' does not exist
```

The line I'm using inside `Start-PodeServer` is:

`Add-PodeSchedule -Name 'Example' -Cron '@annually' -StartTime ([datetime]::MaxValue) -FilePath "getuserdetails.ps1"`

I also tried switching out `-FilePath` for a simple `-ScriptBlock { Get-Process }` to rule out any pathing issues to the file, but I suspect it's not that anyway based on the error I'm seeing.

(The spawning PowerShell window has stopped now - not sure what was causing that yesterday but we can ignore it until it happens again 😄)

**Comment by robinmalik** [comment]
Ok, I binned the existing PowerShell process (the one being used to restart the server each time a new change was made) and started a new process. The server fails to start with:

`Exception calling "AddMinutes" with "1" argument(s): "The added or subtracted value results in an un-representable DateTime.`

Interesting that this wasn't being detected in the original process (which may have had server.ps1 running previously). I'll try constructing a datetime a little differently and see if it starts.

**Comment by robinmalik** [comment]
`(Get-Date).AddDays(9999)` - this will do, and gets the server started. No errors when using `-FilePath` for the schedule now either, but can't see any evidence for the associated script running. The route triggers (as under `Invoke-PodeSchedule` it also fires off a `Send-PodeSignal` which I can see returned). The script being scheduled currently contains (for testing):

```
Write-Output "something" | Out-File $env:temp\aaaaaaaa.txt -Force
Start-Sleep -Seconds 120
```

No file appears in `$env:temp`, and I can't see other spawned processes in Task Manager (although I appreciate I may need to use Process Explorer to dig into that further).

**Comment by robinmalik** [comment]
To save asking me to test other variants:

```
Add-PodeSchedule -Name 'Example' -Cron '@annually' -StartTime (Get-Date).AddDays(9999) -ScriptBlock {
	Write-Output "aaaaaaaaa" | Out-File "podefile.txt" -Force
	Write-Host "$([DateTime]::Now)"
}
```
Sadly still nothing.

**Comment by Badgerati** [comment]
The DateTime/AddMinutes one makes sense, Pode adds a minute to the StartTime to get the next execute time - but Max + 1 will fail. `(Get-Date).AddDays(9999)` is fine, or `.AddYears(1000)` to be extra safe :) Defintiely shows the need for specific routine logic, rather than hacking schedules.

I tried your example, as:
```powershell
Start-PodeServer {
    Add-PodeEndpoint -Address * -Port 8085 -Protocol Http
    New-PodeLoggingMethod -Terminal | Enable-PodeErrorLogging

    Add-PodeSchedule -Name 'Example' -Cron '@annually' -StartTime (Get-Date).AddDays(9999) -ScriptBlock {
        Write-Output "aaaaaaaaa" | Out-File $env:temp\aaaaaaaa.txt -Force
        Write-Host "$([DateTime]::Now)"
    }

    Add-PodeRoute -Method Get -Path '/run' -ScriptBlock {
        Invoke-PodeSchedule -Name 'Example'
    }
}
```

But I get a file generated 🤔 
![image](https://user-images.githubusercontent.com/1483395/147113951-d2fab316-47c3-42ba-b235-62496e44d99c.png)

using a FilePath:
```powershell
Add-PodeSchedule -Name 'Example' -Cron '@annually' -StartTime (Get-Date).AddDays(9999) -FilePath ./schedule-file.ps1
```

With a file containing:
```powershell
return {
    Write-Output "something" | Out-File $env:temp\aaaaaaaa.txt -Force
    Write-Host "$([DateTime]::Now)"
}
```

Also works.

If you add the error logging line to see if there's any errors outputted, or if you already have it, have you got a fuller script I could glance at? (just one that's a schedule+route that doesn't work is good)

**Comment by robinmalik** [comment]
Ah, thank you! Using your example I get the same behaviour as yourself 👍 I thought this helped me narrow down the problem - that `Invoke-PodeSchedule` would trigger fine within `Add-PodeRoute`, but not, as I'm attempting to do, inside `Add-PodeSignalRoute`.

However after rejigging the file to put all schedules in order, followed by all routes, restarting the server in a new PowerShell process, it works inside the signal route too 🥳  After I realised any associated scripts linked to schedules had to be inside `{ }` I was able to get my test script running too.

It's a bit odd though - I feel like sometimes restarting the server within the same PowerShell process/session doesn't always clean up everything (e.g. adding a (simple) new GET route, saving server.ps1 and having it auto-restart and the route returns a 404).

Anyway, this particular issue is solved now. Thanks again for your stellar help :)

**Comment by Badgerati** [comment]
No worries! :)

For the auto-restarting, adding anything new directly in `Start-PodeServer` [won't be detected on auto-restarts](https://badgerati.github.io/Pode/Tutorials/Restarting/Overview/); you need to stop/start the server fully. This is because an auto-restart just re-runs the scriptblock it originally started with.

You can get it to pick up new routes if you put `Add-PodeRoute`, and others, into separate files and dot source them in - that will cause the file to be re-invoked each time, and new routes to be added (or old ones removed). Works the same for schedules, timers, middleware, etc.

**Comment by robinmalik** [comment]
Gotcha re: restarting and code inside `Start-PodeServer` 👍 I was actually just putting the route code into a separate files for a routes folder. `Use-PodeRoutes -Path "routes"` inside `Start-PodeServer.ps1` seems to detect newly added route files without a full restart which is great. Ah yes, just checked the underlying codebase and `Use-PodeScript` is dot sourcing them :)
