### ISSUE TITLE
Run Pode in the background (asynchronous)

### ISSUE THREAD

**Issue by pcgeek86** [Badgerati/Pode#909]
### Question

I need to start Pode, but run it asynchronously. I can't seem to find any parameters on `Start-PodeServer` that would allow me to accomplish that. Any thoughts?

Edit: Google isn't much help either.

**Comment by Badgerati** [comment]
Hi @pcgeek86,

There's nothing built into Pode to do this, yet; but you can run Pode within `Start-Job`. I did look into having an `-AsJob` parameter (#553), but stopping the job took a long time due to there being no way to force kill a job (https://github.com/PowerShell/PowerShell/issues/12897).

I've been meaning to come back to it actually, as I've had some thoughts about how to implement this after doing the middleware for IIS.

**Comment by pcgeek86** [comment]
Thank you, that will actually work really well for my use case. 

### Use Case

I am implementing an oAuth client, so I need to spin up a temporary web server to handle the response from the identity provider.

**Comment by Badgerati** [comment]
Aah, I'm guessing this is for the ReturnUrl part of OAuth? If it's only for a single route to be hit once then, then using `Close-PodeServer` at the end of that route will close the server immediately; no need for jobs or the like :)

**Comment by pcgeek86** [comment]
@Badgerati Yeah it's the `RedirectUri` or whatever they want to call it. I just implemented Google oAuth for this new [YouTube PowerShell module](https://github.com/pcgeek86/youtube/) I created over the weekend. Good tip to use `Close-PodeServer`! Nice. 😎
