### ISSUE TITLE
auth WindowsAD timeout

### ISSUE THREAD

**Issue by phand00** [Badgerati/Pode#913]
### Describe the Bug
Add a login auth on windows ad

### Steps To Reproduce
New-PodeAuthScheme -Basic | Add-PodeAuthWindowsAd -Name 'Login' 

### Expected Behavior
Add-PodeRoute -Method Get -Path '/api/user/:username/invite' -Authentication 'Login' -ScriptBlock {
  #Some stuff here for this route 
}

### Platform
 - OS: Windows Server 2019 domain joined 
 - Browser: Firefox and Chrome 
 - Versions: 
   - Pode: 2.4.2
   - PowerShell: 5.2 

### Additional Context
start pode on the shell with
> start pode -verbose

Nothing happen until the client received a timeout...

Probably I miss something... thanks for your help

**Comment by Badgerati** [comment]
Hi @phand00,

I'm guessing the timeout is from when the `/api/user/:username/invite` route is called?

If your AD happens to have a lot of groups, try using `-NoGroups` on `Add-PodeAuthWindowsAd`:
```powershell
New-PodeAuthScheme -Basic | Add-PodeAuthWindowsAd -Name 'Login' -NoGroups
```

This will stop Pode from getting all the groups a user is a member of, and should speed up the auth :)

Hope that helps!

**Comment by phand00** [comment]
Hi Badgerati,

I confirm that the -NoGroups works. But, it also means i won't be able to check the groups of the user? Is there a way to handle or optimize the request done by the WindowsAD module? 

I just don't understarnd why it's taking so long to retreive all the groups of the user and if I do a simple ldap query or net user /domain I was able to retreive if pretty fast. I know i have thousands of groups in our ad. But each user a finite number of groups. I test it with a user that only has 10 groups and I have a timeout. 

Thanks for your help

Thanks

**Comment by Badgerati** [comment]
Hi @phand00,

It's because the query at the moment is recursive. The user might only be in 10 groups directly, but those groups can be in groups, and they can be in groups, etc. So it depends how deep that tree goes.

The query being used is the fastest I could find, so if there's a way to optimise it then suggestions are welcome!
```powershell
$query = "(member:1.2.840.113556.1.4.1941:=$($DistinguishedName))"
$Connection.Searcher = New-Object System.DirectoryServices.DirectorySearcher $Connection.Entry
$null = $Connection.Searcher.PropertiesToLoad.Add('samaccountname')
$Connection.Searcher.filter = $query
$groups = @($Connection.Searcher.FindAll().Properties.samaccountname)
```

I have noted down a third option for groups though, which is to only get the direct groups - because that would be much faster.

At the moment there's no way to customise it, without editing the module.

**Comment by phand00** [comment]
Hi Badgerati,

I would say that in powershell we can do something like this and it's pretty fast: https://www.sysadmins.lv/blog-en/efficient-way-to-get-ad-user-membership-recursively-with-powershell.aspx 
I see that you hare using ldap query and not AD cmdlet, but we can probably do the same loop validation as the powershell example with ldap query. 

Like you suggest in your previous post, I would also suggest a -Recursive or -RecursiveGroup or -NestedGroup parameter. Leaving the -Group non recursive might be a nice addon too.

And finally. Adding something like -Properties and being able to supply additional attributes to return into the user hash table might be very useful in the scriptblock section. For example, we might add -Properties extensionattribute14 and in the scriptblock we can validate the content of the hash key $user["extensionattribute14"] for a specific value?

**Comment by Badgerati** [comment]
Hi @phand00,

That's actually the way the old logic use to work before I found the `member:1.2.840.113556.1.4.1941` shortcut; the recursive method like that works, but it was actually much slower! It could be different with the ActiveDirectory module, but as you've spotted Pode uses the DirectoryServices methods. The reason for using the DS methods was so people didn't have to install RSAT as a requirement.

The switch would have to be `-DirectGroups`, and leave current groups logic as recursive. Changing the existing logic to direct instead of recursive could break anybody who currently relies on that implementation. (I can note down to switch this logic to direct first in a future v3.0 release though).

Yep, totally agree with `-Property`! :)

I think there could be a couple ways of speeding this up then:
1. Add a `-DirectGroups` switch to get groups non-recursively
2. Check if the `ActiveDirectory` module exists when `Add-PodeAuthWindowsAd` is called (on Windows). Or, similar to how there's an `-OpenLDAP` switch, have an `ADModule` switch.
    a. If it existing (or switch supplied), `Import-Module` (and export for Pode, if auto-imports restricted)
    b. Flag that we're using the AD module
    c. When it comes to authenticating a user, instead of using the DS methods, use the AD module

Combination of the two should help to speed things up 🤔

**Comment by phand00** [comment]
ok

I'll check for this in futur release. As of now, I'll implement in my own scriptblock a manual check with ad cmdlet.

Thanks a lot for your help. 
And keep up the good work. Pode is a fantastic tool with a lot of potential.

**Comment by pcgeek86** [comment]
@Badgerati I have an idea, although full disclosure, I don't use this feature at all, yet.

* **Option 4**: Cache user-group memberships periodically, using a timer-based task. Increase the number of threads on the Pode server, to free up additional runspaces for executing the background task and responding to API routes. Calls to the API route reads from JSON cache instead of directly from Active Directory. Provide a feature flag to enable or disable caching of user-group memberships.

**Comment by Badgerati** [comment]
@pcgeek86 Ooo, it'd probably have to be a schedule so it doesn't impact anything else; I can see it taking quite some time to run for some domains!

But as an optional switch, it should be feasible 🤔  I'll have a play with the idea when I get chance, thanks!

**Comment by Badgerati** [comment]
Hi @phand00,

I've done some work on this, and in the above commit there are now `-DirectGroups` and `-ADModule` switches available on `Add-PodeAuthWindowsAd`.

I've done some initial testing with them, and each seems to work. When you specify `-ADModule` this will auto-import the AD module for you as well.

So:
```powershell
New-PodeAuthScheme -Basic | Add-PodeAuthWindowsAd -Name 'Login' -DirectGroups
New-PodeAuthScheme -Basic | Add-PodeAuthWindowsAd -Name 'Login' -ADModule
New-PodeAuthScheme -Basic | Add-PodeAuthWindowsAd -Name 'Login' -ADModule -DirectGroups

# etc
```
