### ISSUE TITLE
Pode should listen on IPv6 network addresses

### ISSUE THREAD

**Issue by pcgeek86** [Badgerati/Pode#915]
### Describe the Bug

Pode should listen on IPv6 network interfaces.

### Steps To Reproduce

```pwsh
Start-PodeServer -ScriptBlock {
  Add-PodeEndpoint -Address '::' -Port 34001 -Protocol http

  Add-PodeRoute -Method Get -Path /meat -ScriptBlock {
    Write-Host -Object (Get-Random -InputObject @('Bacon', 'Sausage', 'Steak', 'Italian Sausage', 'Beef'))
    Write-PodeTextResponse -Value success
  }
}
```

On the client ...

```pwsh
Invoke-RestMethod -Uri http://[::1]:34001/meat
```

Result ...

```
Invoke-RestMethod: No connection could be made because the target machine actively refused it.
```

### Expected Behavior

Pode should listen on IPv6 network interfaces.

### Screenshots

![image](https://user-images.githubusercontent.com/466713/151684737-cb3e1984-4408-4fe7-b642-7a092a817313.png)

### Platform
 - OS: Windows 11 Build 22523
 - Browser: n/a
 - Versions:
   - Pode: 2.5.2
   - PowerShell: 7.2.1

**Comment by Badgerati** [comment]
Hey @pcgeek86,

I think I might have found the issue; what happens if you change the regex at the following line: https://github.com/Badgerati/Pode/blob/337f10f409e3407f74ad8ec4b1e7954623c856e3/src/Private/Helpers.ps1#L168

to `\[[a-f0-9\:]+\]|((\d+\.){3}\d+)|\:\:\d*|\*|all` instead?

I did that, and then listening on `::` could be called via `[::1]`.

**Comment by pcgeek86** [comment]
@Badgerati That seems to work on my system.
