### ISSUE TITLE
relative path cause running error, what missing for correct execution?

### ISSUE THREAD

**Issue by ericxin1982** [Badgerati/Pode#934]
![image](https://user-images.githubusercontent.com/9047436/153357136-b2f4d481-6fbf-49cb-b58a-c59be8b58847.png)
![image](https://user-images.githubusercontent.com/9047436/153357395-7492ae3e-3622-4828-86a3-8ca871636a7c.png)

What should I set for the relative path?

Thanks
Eric Xin

**Comment by Badgerati** [comment]
Hi @ericxin1982,

The first error for "cannot index into a null array" is actually fixed in v2.6.0. You'll still get an error, but it'll be the proper "can't find this file" error.

The other error, is actually a bug! when `Start-PodeServer` goes to load the file, it's using:
```powershell
$FilePath = Get-PodeRelativePath -Path $FilePath -Resolve -TestPath
```

and not something like:
```powershell
$FilePath = Get-PodeRelativePath -Path $FilePath -Resolve -TestPath -JoinRoot -RootPath $MyInvocation.PSScriptRoot
```
